### ISSUE TITLE
Crash when i got a fish (NoSuchMethodError)

### ISSUE THREAD

**Issue by Luicuelo** [NightKosh/Advanced-Fishing#30]
Playing RLCraft 2.9.2 , Advanced-Fishing-1.12.2-1.3.3

When i get a fish  (FishingEventHandler) crash whit NoSuchMethodError:

java.lang.NoSuchMethodError: levelup2.skills.SkillRegistry.getSkillLevel(Lnet/minecraft/entity/player/EntityPlayer;Ljava/lang/String;)I
        at net.theawesomegem.fishingmadebetter.util.LevelUpLoot.getFishingLoot(LevelUpLoot.java:42) ~[LevelUpLoot.class:2.2.6]
        at net.theawesomegem.fishingmadebetter.util.LevelUpLoot.doLevelUpLoot(LevelUpLoot.java:20) ~[LevelUpLoot.class:2.2.6]
        at net.theawesomegem.fishingmadebetter.common.event.FishingEventHandler.onPlayerFish(FishingEventHandler.java:224) ~[FishingEventHandler.class:2.2.6]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1841_FishingEventHandler_onPlayerFish_ItemFishedEvent.invoke(.dynamic) ~[?:?]

**Comment by Luicuelo** [comment]
I think the problem is with Level Up! mod. I had an incompatible version.
